import { EmojiAvatar } from "../interfaces";

export const EMOJI_AVATARS: EmojiAvatar[] = [
    { id: "polar-bear", emoji: "🐻‍❄️" },
    { id: "unicorn", emoji: "🦄" },
    { id: "octopus", emoji: "🐙" },
    { id: "turtle", emoji: "🐢" },
    { id: "flamingo", emoji: "🦩" },
    { id: "raccoon", emoji: "🦝" },
    { id: "butterfly", emoji: "🦋" },
    { id: "parrot", emoji: "🦜" },
    { id: "rockStar", emoji: "🧑‍🎤" },
    { id: "astronaut", emoji: "🧑‍🚀" },
    { id: "artist", emoji: "🧑‍🎨" },
    { id: "manDancing", emoji: "🕺" },
    { id: "womanDancing", emoji: "💃" },
    { id: "manRunning", emoji: "🏃‍♂️" },
    { id: "womanRunning", emoji: "🏃‍♀️" },
    { id: "balletDancer", emoji: "🩰" },
    { id: "genie", emoji: "🧞" },
    { id: "wizard", emoji: "🧙‍♂️" },
    { id: "witch", emoji: "🧙‍♀️" },
    { id: "elfMan", emoji: "🧝‍♂️" },
    { id: "elfWoman", emoji: "🧝‍♀️" },
    { id: "vampireMan", emoji: "🧛‍♂️" },
    { id: "vampireWoman", emoji: "🧛‍♀️" },
    { id: "superhero", emoji: "🦸‍♂️" },
    { id: "superheroWoman", emoji: "🦸‍♀️" },
    { id: "merman", emoji: "🧜‍♂️" },
    { id: "mermaid", emoji: "🧜‍♀️" },
    { id: "angel", emoji: "👼" },
    { id: "princess", emoji: "👸" },
    { id: "prince", emoji: "🤴" },
    { id: "ninja", emoji: "🥷" },
    { id: "robot", emoji: "🤖" },
    { id: "pirateFlag", emoji: "🏴‍☠️" },
    { id: "kiwi", emoji: "🥝" },
    { id: "crystal-ball", emoji: "🔮" },
    { id: "rocket", emoji: "🚀" },
    { id: "teddy-bear", emoji: "🧸" },
    { id: "microbe", emoji: "🦠" },
    { id: "gemstone", emoji: "💎" },
    { id: "cupcake", emoji: "🧁" },
    { id: "donut", emoji: "🍩" },
    { id: "watermelon", emoji: "🍉" },
  ];
